# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false

    [goldmark.parser.attribute]
      block = true

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]
          
  [goldmark.renderer]
    unsafe = true

[params]
  math = false

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4

